trigger:
    branches:
        include: ['*']
    tags:
        include: ['*']

jobs:
    - job: posix_tests
      displayName: POSIX
      strategy:
          matrix:
              #linux
              ubuntu-16-py27:
                  imageName: ubuntu-16.04
                  pythonVersion: '2.7'
              ubuntu-16-py36:
                  imageName: ubuntu-16.04
                  pythonVersion: '3.6'

              #High Sierra
              macOS-10.13-py27:
                  imageName: macos-10.13
                  pythonVersion: '2.7'
              macOS-10.13-py37:
                  imageName: macos-10.13
                  pythonVersion: '3.6'

#              #Mojave
#              macOS-10.14-py27:
#                  imageName: macos-10.14
#                  pythonVersion: '2.7'
#              macOS-10.14-py37:
#                  imageName: macos-10.14
#                  pythonVersion: '3.6'

      pool:
          vmImage: $(imageName)

      steps:
          - task: UsePythonVersion@0
            inputs:
                versionSpec: '$(pythonVersion)'
            displayName: Install Python (using Azure task)
          - script: ./configure
            displayName: Run configure
          - script: ./bin/pytest -vvs tests/commoncode
            displayName: Run tests

    - job : win_tests
      displayName: Win
      strategy:
          matrix:
              Windows_2016_py27_x86:
                  imageName: vs2017-win2016
                  pythonVersion: '2.7'
                  architecture: x86
              Windows_2016_py36_x86:
                  imageName: vs2017-win2016
                  pythonVersion: '3.6'
                  architecture: x86
#              Windows_2012_py27_x86:
#                  imageName: vs2015-win2012r2
#                  pythonVersion: '2.7'
#                  architecture: x86
#              Windows_2012_py36_x86:
#                  imageName: vs2015-win2012r2
#                  pythonVersion: '3.6'
#                  architecture: x86
#              Windows_2019_py27_x86:
#                  imageName: windows-2019
#                  pythonVersion: '2.7'
#                  architecture: x86
#              Windows_2019_py36_x86:
#                  imageName: windows-2019
#                  pythonVersion: '3.6'
#                  architecture: x86
#              Windows_2016_py27_x64:
#                  imageName: vs2017-win2016
#                  pythonVersion: '2.7'
#                  architecture: x64
#              Windows_2016_py36_x64:
#                  imageName: vs2017-win2016
#                  pythonVersion: '3.6'
#                  architecture: x64
#              Windows_2012_py27_x64:
#                  imageName: vs2015-win2012r2
#                  pythonVersion: '2.7'
#                  architecture: x64
#              Windows_2012_py36_x64:
#                  imageName: vs2015-win2012r2
#                  pythonVersion: '3.6'
#                  architecture: x64
#              Windows_2019_py27_x64:
#                  imageName: windows-2019
#                  pythonVersion: '2.7'
#                  architecture: x64
#              Windows_2019_py36_x64:
#                  imageName: windows-2019
#                  pythonVersion: '3.6'
#                  architecture: x64

      pool:
          vmImage: $(imageName)

      steps:
          - task: UsePythonVersion@0
            inputs:
                versionSpec: '$(pythonVersion)'
                architecture: $(architecture)
            displayName: Install Python (using Azure task)

          - script: configure
            displayName: Run configure
          - script: bin\pytest -vvs tests\commoncode
            displayName: Run tests
